export const PermissionCodes = {
    salesAccess: 'sales.access',
    salesCreate: 'sales.create',
    salesUpdate: 'sales.update',
    salesDelete: 'sales.delete',
    salesPay: 'sales.pay',
    salesCancelHistorical: 'sales.cancel.historical',
    cashAccess: 'cash.access',
    cashOpen: 'cash.open',
    cashClose: 'cash.close',
    cashWithdraw: 'cash.withdraw',
    cashIncome: 'cash.income',
    cashDrawerManage: 'cash.drawer.manage',
    cashDrawerViewAll: 'cash.drawer.view_all',
    cashHistoryExport: 'cash.history.export',
    branchesViewAll: 'branches.view_all',
    branchesManage: 'branches.manage',
    usersManage: 'users.manage',
    customersDelete: 'customers.delete',
    salesPriceOverride: 'sales.override_price',
    salesRemitoAmounts: 'sales.remito.amounts',
    banksManage: 'banks.manage',
    chequesManage: 'cheques.manage',
    cashDrawerAssign: 'cash.drawer.assign',
    productsViewCost: 'products.view_cost',
    productsDelete: 'products.delete',
    categoriesManage: 'categories.manage',
    stockManage: 'stock.manage',
    stockTransfer: 'stock.transfer',
    dashboardViewFinancials: 'dashboard.view_financials',
    reportsAudit: 'reports.audit',
    reportsSalesModel: 'reports.sales.model',
    reportsSalesComparison: 'reports.sales.comparison',
    reportsSalesTransport: 'reports.sales.transport',
    reportsSalesChannel: 'reports.sales.channel',
    reportsSalesChannelBrand: 'reports.sales.channel_brand',
    reportsSalesBrand: 'reports.sales.brand',
    reportsSalesRanking: 'reports.sales.ranking',
    reportsSalesDailyControl: 'reports.sales.daily_control',
    reportsDebtors: 'reports.debtors',
    reportsCash: 'reports.cash',
    reportsStock: 'reports.stock',
    suppliersManage: 'suppliers.manage',
    purchasesAccess: 'purchases.access',
    purchasesCreate: 'purchases.create',
    purchasesUpdate: 'purchases.update',
    purchasesPay: 'purchases.pay',
    purchasesCancel: 'purchases.cancel',
    productsCostPriceAlert: 'products.cost_price_alert'
} as const;

export type PermissionCode = typeof PermissionCodes[keyof typeof PermissionCodes];

export const PermissionCatalog: ReadonlyArray<{ code: PermissionCode; label: string; description: string }> = [
    { code: PermissionCodes.salesAccess, label: 'Ventas: acceso', description: 'Permite ingresar al modulo de ventas.' },
    { code: PermissionCodes.salesCreate, label: 'Ventas: crear', description: 'Permite registrar ventas nuevas.' },
    { code: PermissionCodes.salesUpdate, label: 'Ventas: editar', description: 'Permite actualizar ventas existentes.' },
    { code: PermissionCodes.salesDelete, label: 'Ventas: eliminar', description: 'Permite eliminar ventas.' },
    { code: PermissionCodes.salesPay, label: 'Ventas: cobrar', description: 'Permite registrar cobros y pagos.' },
    { code: PermissionCodes.salesCancelHistorical, label: 'Ventas: cancelar históricas', description: 'Permite cancelar ventas de sesiones de caja cerradas.' },
    { code: PermissionCodes.cashAccess, label: 'Caja: acceso', description: 'Permite ingresar al modulo de caja.' },
    { code: PermissionCodes.cashOpen, label: 'Caja: abrir', description: 'Permite abrir una caja.' },
    { code: PermissionCodes.cashClose, label: 'Caja: cerrar', description: 'Permite cerrar una caja.' },
    { code: PermissionCodes.cashWithdraw, label: 'Caja: extracciones', description: 'Permite registrar extracciones de efectivo y transferencias entre cajas.' },
    { code: PermissionCodes.cashIncome, label: 'Caja: registrar ingreso', description: 'Permite ver y registrar ingresos manuales de efectivo en la caja.' },
    { code: PermissionCodes.cashDrawerManage, label: 'Caja: administrar', description: 'Permite administrar cajas y configuraciones.' },
    { code: PermissionCodes.cashDrawerViewAll, label: 'Caja: ver otras cajas', description: 'Permite ver y operar cajas distintas a la asignada.' },
    { code: PermissionCodes.cashHistoryExport, label: 'Caja: exportar', description: 'Permite exportar historial de caja.' },
    { code: PermissionCodes.branchesViewAll, label: 'Sucursales: ver todas', description: 'Permite ver y operar todas las sucursales. Sin este permiso, el usuario queda restringido a las sucursales que se le asignen.' },
    { code: PermissionCodes.branchesManage, label: 'Sucursales: administrar', description: 'Permite crear, editar y eliminar sucursales.' },
    { code: PermissionCodes.usersManage, label: 'Usuarios: administrar', description: 'Permite gestionar usuarios y perfiles de acceso.' },
    { code: PermissionCodes.customersDelete, label: 'Clientes: eliminar', description: 'Permite eliminar clientes.' },
    { code: PermissionCodes.salesPriceOverride, label: 'Ventas: sobreescribir precio', description: 'Permite modificar precios durante la venta.' },
    { code: PermissionCodes.salesRemitoAmounts, label: 'Ventas: remito con importes', description: 'Permite descargar el remito de la venta con precios. Sin este permiso, solo el remito de traslado sin importes.' },
    { code: PermissionCodes.banksManage, label: 'Bancos: administrar', description: 'Permite administrar bancos.' },
    { code: PermissionCodes.chequesManage, label: 'Cheques: administrar', description: 'Permite administrar cheques.' },
    { code: PermissionCodes.cashDrawerAssign, label: 'Caja: asignar', description: 'Permite reasignar cajas entre usuarios.' },
    { code: PermissionCodes.productsViewCost, label: 'Productos: ver costo', description: 'Permite ver la columna de costo en la lista y edición de productos.' },
    { code: PermissionCodes.productsDelete, label: 'Productos: eliminar', description: 'Permite eliminar productos.' },
    { code: PermissionCodes.categoriesManage, label: 'Categorías: administrar', description: 'Permite crear, editar y eliminar categorías de producto.' },
    { code: PermissionCodes.stockManage, label: 'Stock: cargar', description: 'Permite cargar y ajustar stock de productos.' },
    { code: PermissionCodes.stockTransfer, label: 'Stock: transferir entre sucursales', description: 'Permite transferir stock entre las sucursales asignadas al usuario (o todas, si tiene ese permiso).' },
    { code: PermissionCodes.dashboardViewFinancials, label: 'Dashboard: ver montos', description: 'Permite ver importes y montos de dinero en el panel.' },
    { code: PermissionCodes.reportsAudit, label: 'Reportería: auditoría', description: 'Permite ver el reporte de auditoría de acciones de los usuarios.' },
    { code: PermissionCodes.reportsSalesModel, label: 'Reportería: ventas por modelo', description: 'Reporte de ventas/ganancia y rentabilidad por modelo.' },
    { code: PermissionCodes.reportsSalesComparison, label: 'Reportería: comparativo de ventas', description: 'Reporte comparativo de ventas entre fechas.' },
    { code: PermissionCodes.reportsSalesTransport, label: 'Reportería: ventas por instalador/vehículo', description: 'Reporte de ventas por instalador o vehículo.' },
    { code: PermissionCodes.reportsSalesChannel, label: 'Reportería: ventas por canal', description: 'Reporte de ventas por canal.' },
    { code: PermissionCodes.reportsSalesChannelBrand, label: 'Reportería: ventas por canal y marca', description: 'Reporte de ventas por canal y marca.' },
    { code: PermissionCodes.reportsSalesBrand, label: 'Reportería: ventas por marca', description: 'Reporte de ventas por marca.' },
    { code: PermissionCodes.reportsSalesRanking, label: 'Reportería: ranking de artículos', description: 'Ranking de artículos más vendidos.' },
    { code: PermissionCodes.reportsSalesDailyControl, label: 'Reportería: control diario de ventas', description: 'Detalle operativo de ventas, referencias, canjes y baterías vendidas.' },
    { code: PermissionCodes.reportsDebtors, label: 'Reportería: clientes deudores', description: 'Reporte de clientes con saldo pendiente en cuenta corriente.' },
    { code: PermissionCodes.reportsCash, label: 'Reportería: caja por motivo', description: 'Reporte de movimientos de caja por motivo (salida/pase/gasto).' },
    { code: PermissionCodes.reportsStock, label: 'Reportería: stock por sucursal', description: 'Matriz de stock disponible por producto y sucursal.' },
    { code: PermissionCodes.suppliersManage, label: 'Proveedores: administrar', description: 'Permite gestionar proveedores.' },
    { code: PermissionCodes.purchasesAccess, label: 'Compras: acceso', description: 'Permite ingresar al módulo de compras.' },
    { code: PermissionCodes.purchasesCreate, label: 'Compras: crear', description: 'Permite registrar compras nuevas.' },
    { code: PermissionCodes.purchasesUpdate, label: 'Compras: editar', description: 'Permite editar compras existentes.' },
    { code: PermissionCodes.purchasesPay, label: 'Compras: pagar', description: 'Permite registrar pagos de compras.' },
    { code: PermissionCodes.purchasesCancel, label: 'Compras: cancelar', description: 'Permite cancelar compras.' },
    { code: PermissionCodes.productsCostPriceAlert, label: 'Productos: alerta precio costo', description: 'Muestra alerta cuando hay productos sin precio de costo cargado.' }
];
